version: "3.9"

services:
    webapi:
        container_name: ccsearcher-webapi
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5002:8080"
        networks:
            - ccsearcher
        depends_on:
            - db
    db:
        image: postgres:17
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - ccsearcher
            
networks:
    ccsearcher:
        driver: bridge
        
volumes:
    postgres_data: