// <auto-generated />
using ChanelCategorySearcher.DAI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChanelCategorySearcher.DAI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250212111012_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChanelCategorySearcher.WebApi.DAL.Chanel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Chanels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "IT",
                            Link = "url",
                            Name = "Tom"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Auto",
                            Link = "url",
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Engineer",
                            Link = "url",
                            Name = "Sam"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
